<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>

<pre>
<center><b><h1>ML & DL</b></center>

<center><b><h1>Lab - 9</b></center>
    <center><b><h1>Mansi Fatepara</b></center>
        <center><b><h1>27/01/2026</b></center>
<pre>


# Step 1: Import Libraries

This step imports all necessary libraries for data processing, visualization, and machine learning.


In [59]:
import pandas as pd

In [60]:
import matplotlib.pyplot as plt

# Step 2: Load the Dataset

Load Given dataset - heart.csv


In [61]:
df = pd.read_csv("heart.csv")

# Step 3: Data Overview

In this step, we examine the dataset structure, summary statistics, and check for missing values.


In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [63]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000


# Step 4: Univariate Analysis

Here we visualize the distribution of each feature using histograms.


In [64]:
df.hist(figsize=(12,12))

array([[<Axes: title={'center': 'age'}>, <Axes: title={'center': 'sex'}>,
        <Axes: title={'center': 'cp'}>,
        <Axes: title={'center': 'trestbps'}>],
       [<Axes: title={'center': 'chol'}>,
        <Axes: title={'center': 'fbs'}>,
        <Axes: title={'center': 'restecg'}>,
        <Axes: title={'center': 'thalach'}>],
       [<Axes: title={'center': 'exang'}>,
        <Axes: title={'center': 'oldpeak'}>,
        <Axes: title={'center': 'slope'}>,
        <Axes: title={'center': 'ca'}>],
       [<Axes: title={'center': 'thal'}>,
        <Axes: title={'center': 'target'}>, <Axes: >, <Axes: >]],
      dtype=object)

# Step 5: Bivariate Analysis

This step involves exploring the correlations between features using a heatmap.


In [65]:
import seaborn as sns

In [66]:
%matplotlib qt

In [67]:
sns.heatmap(df.corr(),annot=True)

<Axes: >

# Step 6: Outlier Detection

We visualize potential outliers using boxplots.


In [68]:
df.boxplot()

AssertionError: 7

# Step 7: Split Data into Training and Testing Sets

The dataset is split into training and testing sets for model evaluation.


In [ ]:
x = df.iloc[::,:-1:]

In [ ]:
y = df['target']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=80)

# Step 8: Train Decision Tree

We train a Decision Tree Classifier on the training data. You have to also check for KNeighborsClassifier and GaussianNB


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier()

In [ ]:
model.fit(x_train,y_train)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_predict = model.predict(x_test)

In [ ]:
accuracy_score(y_test,y_predict)

In [ ]:
model.score(x_test,y_test)

# Cross Validation


In [ ]:
from sklearn.model_selection import KFold

In [ ]:
k = KFold(n_splits=10)

In [ ]:
x

In [69]:
for train_index,test_index in k.split(x):
    x_train,x_test = x.values[train_index],x.values[test_index]
    y_train,y_test = y[train_index],y[test_index]
    model1 = DecisionTreeClassifier()
    model1.fit(x_train,y_train)
    print(model1.score(x_test,y_test))

1.0
1.0
1.0
0.970873786407767
1.0
1.0
1.0
1.0
1.0
1.0


In [70]:
from sklearn.model_selection import cross_val_score

In [71]:
cross_val_score(model,x,y,cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
import numpy as np

In [73]:
x1 = np.arange(1,11).reshape(-1,1)

In [74]:
y1 = np.array([0,1,0,1,0,1,0,1,0,1])

In [75]:
for i,j in k.split(x1):
    print("<------>")
    print(x1[i])
    print(x1[j])
    x_train,x_test = x1[i],x1[j]
    y_train,y_test = y1[i],y1[j]
    

<------>
[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[1]]
<------>
[[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[2]]
<------>
[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[3]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[4]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[5]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[6]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
[[7]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]]
[[8]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]]
[[9]]
<------>
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10]]


# Step 11: Train Bagging Classifier

We train a Bagging Classifier with Decision Trees as the base model.


In [76]:
# bagging : no. of model learners na vote levana
# it means model train thai tyre multiple tree bnse jema bdha tree na votes ly ne new feature ne predict thase.

In [77]:
from sklearn.model_selection import train_test_split
x = df.iloc[::,:-1:]
y = df['target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=80)

In [78]:
from sklearn.ensemble import BaggingClassifier

In [79]:
bc = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=5)

In [80]:
bc.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=5)

In [81]:
y_predict = bc.predict(x_test)

In [82]:
accuracy_score(y_test,y_predict)

0.974025974025974

# Step 12: Evaluate Bagging Classifier

The Bagging model is evaluated using accuracy.


# Step 13: Train Random Forest

We train a Random Forest Classifier on the dataset.


In [83]:
from sklearn.ensemble import RandomForestClassifier

In [84]:
rfc = RandomForestClassifier(n_estimators=100,max_features='sqrt')

In [85]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [86]:
y_predict = rfc.predict(x_test)

In [87]:
accuracy_score(y_test,y_predict)

1.0

# Step 14: Feature Importance in Random Forest

We analyze feature importance as determined by the Random Forest model.


In [88]:
rfc.feature_importances_
# ex. heart diesease predict krva mate kya features nu ketlu important che e aapse

array([0.09445576, 0.03065234, 0.14031415, 0.07164022, 0.07548107,
       0.01107841, 0.02116438, 0.11915987, 0.0415831 , 0.12129562,
       0.03245446, 0.14340155, 0.09731908])

In [89]:
rfc.feature_names_in_
# 

array(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'], dtype=object)

# Step 15: Evaluate Random Forest

We evaluate the Random Forest model using accuracy.


# Step 16: Train AdaBoost Classifier

We train an AdaBoost Classifier on the dataset.


In [90]:
from sklearn.ensemble import AdaBoostClassifier

In [91]:
adbc = AdaBoostClassifier(n_estimators=1000)

In [92]:
adbc.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=1000)

# Step 17: Evaluate AdaBoost Classifier

The AdaBoost model is evaluated using accuracy.


In [93]:
y_predict = adbc.predict(x_test)

In [94]:
accuracy_score(y_test,y_predict)

0.9383116883116883

# <---- B ---->


## Cost Complexity Pruning for Decision Tree


In [95]:
clf = DecisionTreeClassifier(random_state=42)
path = clf.cost_complexity_pruning_path(x_train, y_train)
ccp_alphas, impurities = path.ccp_alphas, path.impurities

In [96]:
# when we increse ccp_alphas then it measure the accuracy
clfs = []
for ccp_alpha in ccp_alphas:
    clf = DecisionTreeClassifier(random_state=42, ccp_alpha=ccp_alpha)
    clf.fit(x_train, y_train)
    clfs.append(clf)

In [97]:
clfs = clfs[:-1]
ccp_alphas = ccp_alphas[:-1]

In [98]:
train_scores = [clf.score(x_train,y_train) for clf in clfs]
test_scores = [clf.score(x_test,y_test) for clf in clfs]

In [99]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.plot(ccp_alphas,train_scores, marker='o', label='train', drawstyle='steps-post')
plt.plot(ccp_alphas,test_scores, marker='o', label='test', drawstyle='steps-post')
plt.title('Accuracy v/s Alpha')
plt.xlabel('Alpha')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

## Random Forest with Iterative Training (OOB Error)


In [100]:
# oob_score => if we can use this with warm_start=True then it can automatically testing in this cell also
# i mean jo tme warm_state=True rakso to e automatically testing kri leshe
# warm_start => if mein previous ma jo tree bnavya hshe ane jo e True hshe to juna treene dlt nhi kre ane ae e bdha juna trees ne utilize kri ne reuse krshe
# but if False hsee to enathi e juna bdha trees ne delete kri deshe
# bootstrap = True => if you can use default bootstrap sample? then you can use with True parameter

rf = RandomForestClassifier(oob_score=True, warm_start=True, random_state=42)

oob_error_rates = []
n_estimators_list = list(range(10, 201, 10))

for n in n_estimators_list:
    rf.set_params(n_estimators=n)
    rf.fit(x_train, y_train)
    
    # OOB Error = 1 - OOB Score
    oob_error = 1 - rf.oob_score_
    oob_error_rates.append(oob_error)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:612: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


## Receiver Operating Characteristic (ROC) Analysis


In [ ]:
from sklearn.metrics import roc_curve, auc


y_prob = rf.predict_proba(x_test)[:, 1]

# Calculate ROC curve metrics
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

# Plot ROC Curve
